name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop
      - "snapshot/**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Install sbt
      uses: sbt/setup-sbt@v1
    - name: Check Scala formatting
      run: sbt scalafmtCheckAll
    - name: Deploy sbt-snowplow-release to Maven Central
      if: startsWith(github.ref, 'refs/tags/')
      run: sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.SONA_PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.SONA_PGP_SECRET }}
        SONATYPE_USERNAME: ${{ secrets.SONA_USER }}
        SONATYPE_PASSWORD: ${{ secrets.SONA_PASS }}
